image: golang:1.11

variables:
  PACKAGE_PATH: /go/src/autonomia.digital/tonio/app

stages:
  - build
  - check

  # A hack to make Golang-in-Gitlab happy
.anchors:
  - &install-deps
      apt-get update -qq
      && apt-get install build-essential libgtk-3-dev -qq
  - &inject-gopath
      mkdir -p $(dirname ${PACKAGE_PATH})
      && ln -s ${CI_PROJECT_DIR} ${PACKAGE_PATH}
      && cd ${PACKAGE_PATH}

build:
  stage: build
  before_script:
    - *install-deps
    - *inject-gopath
  script:
    - make deps
    - make build
  artifacts:
    paths:
      - bin/tonio

build-x86:
  image: i386/golang
  stage: build
  before_script:
    - *install-deps
    - *inject-gopath
  script:
    - make deps
    - make build
  artifacts:
    paths:
      - bin/tonio-x86

test:
  stage: check
  before_script:
    - *install-deps
    - *inject-gopath
  script:
    - make deps
    - make test

coverage:
  stage: check
  before_script:
    - *install-deps
    - *inject-gopath
  coverage: '/total:.*?(\d+\.\d+\%)/'
  script:
    - make deps
    - make cover-ci
  artifacts:
    paths:
      - coverage.html

quality:
  stage: check
  before_script:
    - *install-deps
    - *inject-gopath
  script:
    - make deps
    - make quality
