image: golang:1.11

variables:
  PACKAGE_PATH: /go/src/autonomia.digital/tonio/app

stages:
  - build
  - check
  - deploy

  # A hack to make Golang-in-Gitlab happy
.anchors:
  - &install-deps
      apt-get update -qq
      && apt-get install build-essential libgtk-3-dev -qq
  - &inject-gopath
      mkdir -p $(dirname ${PACKAGE_PATH})
      && ln -s ${CI_PROJECT_DIR} ${PACKAGE_PATH}
      && cd ${PACKAGE_PATH}

build:
  stage: build
  before_script:
    - *install-deps
    - *inject-gopath
  script:
    - make deps
    - make build-ci
  artifacts:
    paths:
      - bin/tonio*

test:
  stage: check
  before_script:
    - *install-deps
    - *inject-gopath
  script:
    - make deps
    - make test

coverage:
  stage: check
  before_script:
    - *install-deps
    - *inject-gopath
  coverage: '/total:.*?(\d+\.\d+\%)/'
  script:
    - make deps
    - make cover-ci
  artifacts:
    paths:
      - coverage.html

quality:
  stage: check
  before_script:
    - *install-deps
    - *inject-gopath
  script:
    - make deps
    - make quality

deploy_staging:
  image: olabini/ssh_rsync:0.1
  stage: deploy
  before_script:
  - apt-get update -qq
  - apt-get install gpg -qq
  - 'eval $(ssh-agent -s)'
  - 'ssh-add <(echo "$DEPLOY_STAGING_SSH_PRIVATE_KEY")'
  - mkdir -p ~/.ssh; chmod 700 ~/.ssh
  - 'echo -e "[staging.tonio.app]:2326,[185.108.76.88]:2326 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEiKOqqE2wJo4OnAvgbCPLsnObcSJuoYQU0cW3QRMPqK4XHeo9RTxOE4jt+40Gy3wfzzo7q1fmUJ/QZrORcNI6Y=" >> ~/.ssh/known_hosts'
  - chmod 644 ~/.ssh/known_hosts
  - 'echo "$GPG_SIGNING_SUBKEY" | gpg --import'
  environment:
    name: staging
    url: https://staging.tonio.app
  only:
    - master
  script:
   - 'export DEPLOY_DIR=/home/tonio/tmp/deploy_binaries'
   - 'export DO_SSH="ssh -p2326 tonio@staging.tonio.app "'
   - '$DO_SSH mkdir -p $DEPLOY_DIR'
   - '$DO_SSH rm -rf $DEPLOY_DIR/*'
   - 'BINARY_NAME=$(find bin -name "tonio*" | head -1)'
   - 'echo $BINARY_NAME'
   - 'sha256sum  $BINARY_NAME > $BINARY_NAME.sha256sum'
   - 'gpg --detach-sign --armor  $BINARY_NAME.sha256sum'
   - 'scp -P2326 $BINARY_NAME* tonio@staging.tonio.app:$DEPLOY_DIR/'
   - 'scp -P2326 deployment/* tonio@staging.tonio.app:bin/'
   - '$DO_SSH chmod +x bin/*'
   - '$DO_SSH bin/publish-downloads.sh'

deploy_production:
  image: olabini/ssh_rsync:0.1
  stage: deploy
  before_script:
  - apt-get update -qq
  - apt-get install gpg -qq
  - "eval $(ssh-agent -s)"
  - 'ssh-add <(echo "$DEPLOY_PRODUCTION_SSH_PRIVATE_KEY")'
  - mkdir -p ~/.ssh; chmod 700 ~/.ssh
  - 'echo -e "[tonio.app]:2387,[185.108.76.87]:2387 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBD7qdL4lFlIQwRU2h2fV6oIMBZl1ifd6bbcajd8iRYaFQfVvj7qxGvorfaBETyquGe+lk0xw3NrcJCfK1LvT2Wo=" >> ~/.ssh/known_hosts'
  - chmod 644 ~/.ssh/known_hosts
  environment:
    name: production
    url: https://tonio.app
  when: manual
  only:
    - master
  script:
   - 'ssh -p2387 tonio@tonio.app rm -f /home/tonio/tmp/*'
   - 'cd bin'
   - 'BINARY_NAME=$(ls tonio* )'
   - 'sha256sum  $BINARY_NAME > $BINARY_NAME.sha256sum'
   - 'gpg --detach-sign --armor  $BINARY_NAME.sha256sum'
   - 'scp -P2387 $BINARY_NAME* tonio@tonio.app:/home/tonio/tmp/'
   - 'ssh -p 2387 tonio@tonio.app bin/update-downloads.sh'
