image: golang:1.11

variables:
  PACKAGE_PATH: /go/src/autonomia.digital/tonio/app

stages:
  - build
  - test
  - coverage

  # A hack to make Golang-in-Gitlab happy
.anchors:
  - &install-deps
      apt-get update -qq
      && apt-get install build-essential libgtk-3-dev -qq
  - &inject-gopath
      mkdir -p $(dirname ${PACKAGE_PATH})
      && ln -s ${CI_PROJECT_DIR} ${PACKAGE_PATH}
      && cd ${PACKAGE_PATH}

build:
  stage: build
  before_script:
    - *install-deps
    - *inject-gopath
  script:
    - make deps
    - make build

test:
  stage: test
  before_script:
    - *install-deps
    - *inject-gopath
  script:
    - make deps
    - make test

coverage:
  stage: coverage
  before_script:
    - *install-deps
    - *inject-gopath
  script:
    - make deps
    - make cover-ci
